service: serverless-order-app

provider:
  name: aws
  runtime: nodejs18.x

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/users/{proxy+}
          method: any
    environment:
      DB_URI: ${env:DB_URI} # Pass the environment variable

plugins:
  - serverless-offline
